<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Nglib</RootNamespace>
    <NoWarn>CS1591;CS1572;CS1573;CS1711</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>

    <!-- PACKAGE VERSION : Independante, a incrementer si projet modifie -->
    <Version>1.1.7-beta</Version>
    
    <!-- PACKAGE INFO -->
    <PackageId>Nglib.Data</PackageId>
    <Description>Data access components for databases. Includes generic database connectors, query builder, and DataSet manipulation tools.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    
    <!-- OPENSOURCE : Surcharge des proprietes communes -->
    <RepositoryUrl>https://github.com/NueGy/NgLib</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>nglib;data;sql;orm;datapo;connector;postgresql;sqlserver;sqlite;mysql;querybuilder;opensource</PackageTags>
    <PackageProjectUrl>https://github.com/NueGy/NgLib</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>



	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	
	
  <ItemGroup>
    <ProjectReference Include="..\Nglib\Nglib.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
  </ItemGroup>

</Project>
